const theme={
    light:{
        theme:'light',
        bg:'#FFFFFF',
        // background:'#1F4690',
        txt:'#111111',
        disable:'#78828A',
        disable1:'#434E58',
        icon:'#E3E9ED',
        // box:'#E3E7EC',
        barstyle: 'dark-content',
        input: '#F6F8FE',
        res:require('../../assets/image/building.png'),
        hour:require('../../assets/image/24light.png'),
        msg:require('../../assets/image/d1.png'),
        notification:require('../../assets/image/Notification.png'),
        message:require('../../assets/image/Message.png'),
        filter:require('../../assets/image/Filter1.png'),
        location:require('../../assets/image/airportlocation.jpg'),
        apple:require('../../assets/image/Apple.png'),
        fpb:'#F5F5F5',
        hotelLocation:require('../../assets/image/Location.png'),
        
    },
    dark:{
        theme:'dark',
        bg:'#171725',
        // background:'#009B8D',      
        txt:'#FFFFFF',
        disable:'#F6F8FE',
        disable1:'#F6F8FE',
        icon:'#1D1D2F',
        // box:'#434E58',
        barstyle:'light-content',
        input: '#282837',
        res:require('../../assets/image/buildingdark.png'),
        hour:require('../../assets/image/24dark.png'),
        msg:require('../../assets/image/d2.png'),
        notification:require('../../assets/image/Notificationdark.png'),
        message:require('../../assets/image/Messagedark.png'),
        filter:require('../../assets/image/Filter1dark.png'),
        location:require('../../assets/image/airportlocationdark.jpg'),
        apple:require('../../assets/image/Apple1.png'),
        fpb:'#434E58',
        hotelLocation:require('../../assets/image/Locationdark.png'),
    },
    
};

export default theme;